In [1]:
import numpy as np

In [22]:
initial_state = np.zeros((5,5,20), dtype = int)
for i in range(5):
    for j in range(5):
        if container[i][j] > 0:
            k = container[i][j] - 1
            initial_state[i][j][k] = 1
        else:
            continue

In [42]:
# ind = np.unravel_index(np.argmax(a, axis=None), a.shape)

(1, 1)

In [19]:
i, j = np.where(container == 1)
i = int(i)
j = int(j)
if container[i-1][j] == 0:
    container[i][j] = 0

In [32]:
container
container_temp = container
container_temp

array([[ 0,  0,  0,  0,  0],
       [ 2,  1,  5,  4,  3],
       [11,  9, 10, 19, 20],
       [13, 15, 18, 12, 17],
       [14,  6,  8,  7, 16]])

In [34]:
container_temp = container_temp -1
container_temp

array([[-2, -2, -2, -2, -2],
       [ 0, -1,  3,  2,  1],
       [ 9,  7,  8, 17, 18],
       [11, 13, 16, 10, 15],
       [12,  4,  6,  5, 14]])

In [28]:
container.reshape((1,-1)).shape

(1, 25)

In [41]:
# build the enviroment
random_sequence = [2,1,5,4,3,11,9,10,19,20,13,15,18,12,17,14,6,8,7,16]
container = np.zeros((5,5), dtype = int)
random_sequence_temp = np.array(random_sequence).reshape(4,5)
container[1:,:] = random_sequence_temp
container
class Enviroment(object):
#     the dimension of state: (1,25)
#     the dimension of action: (1,5*5*4-20)
    def __init__(self, container):
        self._container = container
        self.nrows, self.ncols = self._container.shape
        self.reset()
        self.max_reward = self.get_initial_reward()
        
    def reset(self):
        self.container = np.copy(self._container)
        self.init_state = self.container.reshape((1,-1))
        self.total_reward = 0
        self.reward_list = []
        self.result = []
        
    def check_state(self):
        if self.result is None:
            init_value = 1
        elif len(self.result) < 20:
            init_value = self.result[-1]+1  
        else:
            done = True
            current_reward = 0
            return self.container, self.result, self.total_reward, current_reward, done
        current_reward = 0
        for num in range(init_value,21):
            i, j = np.where(self.container == num)
            i = int(i)
            j = int(j)
            if i == 0:
                self.result.append(num)
                self.total_reward = self.total_reward +1
                current_reward = current_reward +1
            elif self.container[i-1][j] == 0:
                self.result.append(num)
                self.total_reward = self.total_reward +1
                self.container[i][j] = 0
                current_reward = current_reward +1
            else:
                break
        if len(self.result) == 20:
            done = True
        else:
            done = False
        return self.container, self.result, self.total_reward, current_reward, done
    
    def check_valid_actions_and_act(self, action):
        """check action is valid, action is move one number left right up down
           action is a tuple(number, direction)
        """
        valid_action = True
        action_num = action[0]
        action_direction = action[1]
        i, j = np.where(self.container == action_num)
        i = int(i)
        j = int(j)
        if i == 0 and action_direction == "up":
            valid_action = False
        if i == self.nrows - 1 and action_direction == "down":
            valid_action = False
        if j == 0 and action_direction == "left":
            valid_action = False
        if i == self.ncols - 1 and action_direction == "right":
            valid_action = False

        if valid_action:
            if action_direction == "up":
                m = i-1
                n = j
            elif action_direction == "down":
                m = i+1
                n = j
            elif action_direction == "left":
                m = i
                n = j -1
            elif action_direction == "right":
                m = i
                n = j+1
            if self.container[m][n] == 0:
                self.container[m][n] = action_num[0]
                self.container[i][j] = 0  
        return valid_action, self.container        
        
    def get_initial_reward(self):
        self.container, self.result, self.total_reward, current_reward, done = self.check_state()
        self.max_reward = 20 - current_reward
        return self.max_reward       

In [47]:
container.shape

(5, 5)

In [43]:
env = Enviroment(container)
env.max_reward

IndexError: list index out of range

In [45]:
len(env.env.result)

NameError: name 'env' is not defined

In [46]:
env = Enviroment(container)

IndexError: list index out of range

In [52]:
x = np.arange(100).reshape((1,-1))

In [57]:
x[:,10]

array([10])

In [58]:
int(x[:,10])

10

In [61]:
x = np.zeros((5,2))
x[0]  = np.arange(2).reshape((1,-1))

In [62]:
x

array([[0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])