# Matrix operation
1. Random generation
2. Matrix construction from array and reshape
3. Matrix Multiplication
4. Matrix Transpose

In [1]:
import numpy as np

In [2]:
# random generation
np.matrix(np.random.random((4, 4)))

matrix([[ 0.98508142,  0.7561882 ,  0.33915109,  0.24475886],
        [ 0.18131152,  0.18507003,  0.68578723,  0.2059457 ],
        [ 0.76205083,  0.47528831,  0.18953237,  0.09401905],
        [ 0.25436264,  0.80758627,  0.76956586,  0.4037462 ]])

In [3]:
np.matrix('1 2; 3 4')

matrix([[1, 2],
        [3, 4]])

In [4]:
# incorrect reshape from on array 
np.matrix(np.array([1, 2, 3, 4, 5, 6]).reshape((4, 4)))

ValueError: cannot reshape array of size 6 into shape (4,4)

In [5]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [6]:
# matrix reshape
A = np.matrix(np.arange(16).reshape((4, 4)))
A

matrix([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [7]:
# matrix transpose
np.transpose(A)

matrix([[ 0,  4,  8, 12],
        [ 1,  5,  9, 13],
        [ 2,  6, 10, 14],
        [ 3,  7, 11, 15]])

In [8]:
# matrix mulitplication
A_left = np.matrix(np.arange(12)).reshape(3, 4)
A_left

matrix([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [9]:
B_right = np.ones((4, 3))
B_right

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [10]:
A_left * B_right

matrix([[  6.,   6.,   6.],
        [ 22.,  22.,  22.],
        [ 38.,  38.,  38.]])

In [11]:
np.dot(A_left, B_right)

matrix([[  6.,   6.,   6.],
        [ 22.,  22.,  22.],
        [ 38.,  38.,  38.]])

In [12]:
# Matrix with by element operation
A_left + 1

matrix([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [13]:
np.sin(A_left)

matrix([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
        [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
        [ 0.98935825,  0.41211849, -0.54402111, -0.99999021]])